site_name: nitorch-fastmath
site_url: https://nitorch-fastmath.readthedocs.io
repo_url: https://github.com/nitorch/nitorch-fastmath
edit_uri: blob/main/docs/md
site_dir: html
docs_dir: md
theme: 
  name: material
plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [..]
        options:
          docstring_style: numpy
          merge_init_into_class: True
          separate_signature: True
          members_order: source
          show_source: False
          show_root_heading: True
          preload_modules: 
          - jitfields
markdown_extensions:
- pymdownx.arithmatex:
    generic: true
extra_javascript:
- javascripts/mathjax.js
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
- Home: index.md
- Installation: install.md
- Getting Started: start.md
- API: 
  - sym: api/sym.md
  - simplex: api/simplex.md
  - reduce: api/reduce.md
  - qr: api/qr.md
  - linalg: api/linalg.md
  - stochastic: api/stochastic.md

watch:
- ../nitorch_fastmath

